const express=require('express')
const db=require('./config')
const credientials=require('./routers/credientialroutes')
const seller=require('./routers/sellerroutes')
const orders=require('./routers/orderroutes')
const app=express()
app.use(express.json())
const usermodel=require('./model/users')
const productmodel=require('./model/products')
const ordermodel=require('./model/order')
usermodel()
productmodel()
ordermodel()
app.use('/api/credientials',credientials)
app.use('/api/seller',seller)
app.use('api/order',orders)
app.listen(3000,()=>{
    console.log("app running on port 3000")
})